# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opt.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'opt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\topt.proto\"\xd4\x01\n\x13OptimizationRequest\x12\x11\n\tstudent_w\x18\x01 \x03(\x05\x12\x13\n\x0b\x63lassroom_w\x18\x02 \x03(\x05\x12\r\n\x05\x64\x61y_w\x18\x03 \x03(\x02\x12\r\n\x05\x64\x61y_5\x18\x04 \x03(\x02\x12\x13\n\x0bstudent_num\x18\x05 \x01(\x05\x12\x15\n\rclassroom_num\x18\x06 \x01(\x05\x12\x0f\n\x07\x64\x61y_num\x18\x07 \x01(\x05\x12\x1e\n\x16schedule_classroom_num\x18\x08 \x01(\x05\x12\x1a\n\x12schedule_class_num\x18\t \x01(\x05\"q\n\x14OptimizationResponse\x12\x11\n\tobj_value\x18\x01 \x01(\x02\x12\x10\n\x08obj_pref\x18\x02 \x01(\x02\x12\r\n\x05obj_w\x18\x03 \x01(\x02\x12\t\n\x01x\x18\x04 \x03(\x02\x12\t\n\x01y\x18\x05 \x03(\x02\x12\x0f\n\x07success\x18\x06 \x01(\x08\x32S\n\x14ScheduleOptimization\x12;\n\x0cschedule_opt\x12\x14.OptimizationRequest\x1a\x15.OptimizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZATIONREQUEST']._serialized_start=14
  _globals['_OPTIMIZATIONREQUEST']._serialized_end=226
  _globals['_OPTIMIZATIONRESPONSE']._serialized_start=228
  _globals['_OPTIMIZATIONRESPONSE']._serialized_end=341
  _globals['_SCHEDULEOPTIMIZATION']._serialized_start=343
  _globals['_SCHEDULEOPTIMIZATION']._serialized_end=426
# @@protoc_insertion_point(module_scope)
